### ISSUE TITLE
竖屏视频压缩后成横屏了而且还拉伸了

### ISSUE THREAD

**Issue by zhanweisun** [Tourenathan-G5organisation/SiliCompressor#109]
竖屏视频压缩后成横屏了而且还拉伸了,
这个问题有人遇到过么,怎么解决?

**Comment by wangcaisheng** [comment]
你这个问题解决了吗？

**Comment by wangcaisheng** [comment]
> 竖屏视频压缩后成横屏了而且还拉伸了,
> 这个问题有人遇到过么,怎么解决?



> 竖屏视频压缩后成横屏了而且还拉伸了,
> 这个问题有人遇到过么,怎么解决?

你这个问题解决了吗？我也遇到了相同的问题

**Comment by zhanweisun** [comment]
需要设置宽高,要不然默认的就是这样.

**Comment by zhangjianwei1** [comment]
这个问题解决了么，我设置了宽高还是出现了这个问题
