### ISSUE TITLE
compressVideo() should accept a Uri, not just File

### ISSUE THREAD

**Issue by tfrysinger** [Tourenathan-G5organisation/SiliCompressor#112]
The input to compress the video should take a Uri argument for the input source as an alternative to a File. This way data could be streamed regardless of the location (I might have a source video on Dropbox for example). Output can still be handled through a File object (although writing output to a Uri would also be helpful).

**Comment by Tourenathan-G5organisation** [comment]
HEllo @tfrysinger 
This is now available in version 2.2.3
