### ISSUE TITLE
 implementation 'com.iceteck.silicompressorr:silicompressor:2.2.2'

### ISSUE THREAD

**Issue by XinYiWorld** [Tourenathan-G5organisation/SiliCompressor#114]
when I add the denpendency,it makes the next errror:
Program type already present: org.aspectj.internal.lang.annotation.ajcDeclareAnnotation

**Comment by ydz00ydz** [comment]
i've met the question too

**Comment by ydz00ydz** [comment]
解决了，原项目中有aspectjrt.jar和isoparser.jar，把他们删了就不冲突了。

**Comment by Tourenathan-G5organisation** [comment]
Hello, this issue should be be solved in the latest version 2.2.3
Check and give feedback

**Comment by 1335987402** [comment]
并没有解决！我现在用的2.2.3，还是有这个冲突
