### ISSUE TITLE
Not working on api 29

### ISSUE THREAD

**Issue by Pirokar** [Tourenathan-G5organisation/SiliCompressor#129]
java.lang.ArithmeticException: divide by zero
imagePath: /storage/emulated/0/WhatsApp/Media/WhatsApp Images/IMG-20191218-WA0017.jpg

**Comment by AnasElshawaf** [comment]
if you are run in android 29 then you have to use scoped storage or for now, you can bypass this issue by using android:requestLegacyExternalStorage=" true" in manifest in the application tag

**Comment by Tourenathan-G5organisation** [comment]
@Pirokar @AnasElshawaf please check v2.2.4 for the fix
