### ISSUE TITLE
GNU license should be added as well

### ISSUE THREAD

**Issue by samirshrestha** [Tourenathan-G5organisation/SiliCompressor#13]
This library is based on VideoCompressor by lalongooo which in turn is based on Telegram. So this library should include the GNU license as well.

**Comment by Tourenathan-G5organisation** [comment]
@samirshrestha OK got it. Thanks for the feedback

**Comment by Tourenathan-G5organisation** [comment]
@samirshrestha, Its done. 
Thanks
