### ISSUE TITLE
Not working on API 29

### ISSUE THREAD

**Issue by Pirokar** [Tourenathan-G5organisation/SiliCompressor#130]
java.lang.ArithmeticException: divide by zero
imagePath: /storage/emulated/0/WhatsApp/Media/WhatsApp Images/IMG-20191218-WA0017.jpg

**Comment by mayurr1512** [comment]
In SilliCompressor.Java File you need to make following changes to support Android 10 : 

private String getFilename(String filename, File file) {
        String ext = ".jpg";
        File fileNew = new File(file, "/IMG_" + new SimpleDateFormat("yyyyMMdd_HHmmss").format(new Date()) + ext);
        try {
            fileNew.createNewFile();
            return fileNew.getAbsolutePath();
        } catch (IOException e) {
            e.printStackTrace();
        }
        return fileNew.getAbsolutePath();
    }

**Comment by LichKing255** [comment]
> In SilliCompressor.Java File you need to make following changes to support Android 10 :
> 
> private String getFilename(String filename, File file) {
> String ext = ".jpg";
> File fileNew = new File(file, "/IMG_" + new SimpleDateFormat("yyyyMMdd_HHmmss").format(new Date()) + ext);
> try {
> fileNew.createNewFile();
> return fileNew.getAbsolutePath();
> } catch (IOException e) {
> e.printStackTrace();
> }
> return fileNew.getAbsolutePath();
> }

not work.

**Comment by mayurr1512** [comment]
> > In SilliCompressor.Java File you need to make following changes to support Android 10 :
> > private String getFilename(String filename, File file) {
> > String ext = ".jpg";
> > File fileNew = new File(file, "/IMG_" + new SimpleDateFormat("yyyyMMdd_HHmmss").format(new Date()) + ext);
> > try {
> > fileNew.createNewFile();
> > return fileNew.getAbsolutePath();
> > } catch (IOException e) {
> > e.printStackTrace();
> > }
> > return fileNew.getAbsolutePath();
> > }
> 
> not work.


Its working fine on my side. Please review the code I have provided

**Comment by Tourenathan-G5organisation** [comment]
@Pirokar @LichKing255 Please check the new version release 2.2.4
