### ISSUE TITLE
not compress in api 29 

### ISSUE THREAD

**Issue by drsoosmar** [Tourenathan-G5organisation/SiliCompressor#149]
hello , this library not compress in api 29
for example samsung galaxy a20 android 10
Do you have a way to solve this problem?

**Comment by AnasElshawaf** [comment]
if you are run in android 29 then you have to use scoped storage or for now, you can bypass this issue by using android:requestLegacyExternalStorage=" true" in manifest in the application tag

**Comment by Tourenathan-G5organisation** [comment]
@drsoosmar @AnasElshawaf This is now fixed in the latest release 2.2.4
