### ISSUE TITLE
unable to compress gallery video

### ISSUE THREAD

**Issue by narendra88** [Tourenathan-G5organisation/SiliCompressor#15]
I tried this code for compressing gallery video --- 
```

    private void galleryIntent() {
        Intent intent = new Intent(Intent.ACTION_GET_CONTENT);
        intent.setAction(Intent.ACTION_GET_CONTENT);
        intent.setType("video/mp4");
        try {
            capturedUri = Uri.fromFile(createMediaFile(TYPE_VIDEO));
        } catch (IOException e) {
            e.printStackTrace();
        }
        intent.putExtra(MediaStore.EXTRA_OUTPUT, capturedUri);
        Log.d(LOG_TAG, "VideoUri: "  + capturedUri.toString());
        startActivityForResult(intent, RESQUEST_TAKE_VIDEO);


    }

```
       // Method which will process the captured image
    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        //verify if the image was gotten successfully
         if (requestCode == RESQUEST_TAKE_VIDEO && resultCode == RESULT_OK){
            if (data.getData() != null) {
                //create destination directory
                File f = new File(Environment.getExternalStorageDirectory().getAbsolutePath() + "/" + getPackageName() + "/media/videos");
                if (f.mkdirs() || f.isDirectory())
                    //compress and output new video specs
                    new VideoCompressAsyncTask(this).execute(data.getData().toString(), f.getPath());
            }
        }

    }

    private File createMediaFile(int type) throws IOException {

        // Create an image file name
        String timeStamp = new SimpleDateFormat("yyyyMMdd_HHmmss").format(new Date());
        String fileName = type == 1 ? "JPEG_" + timeStamp + "_" : "VID_" + timeStamp + "_";
        File storageDir = Environment.getExternalStoragePublicDirectory(
                type == 1 ? Environment.DIRECTORY_PICTURES : Environment.DIRECTORY_MOVIES);
        File file = File.createTempFile(
                fileName,  /* prefix */
                type == 1 ? ".jpg" : ".mp4",         /* suffix */
                storageDir      /* directory */
        );

        // Save a file: path for use with ACTION_VIEW intents
        mCurrentPhotoPath = "file:" + file.getAbsolutePath();
        Log.d(LOG_TAG, "mCurrentPhotoPath: " + mCurrentPhotoPath);
        return file;
    }

But, its not working, getting failed. What I am doing wrong here?

```

```

**Comment by Virendra-Varma** [comment]
hi @narendra88, how did you Solve this issue?

**Comment by Virendra-Varma** [comment]
need to use Asynctask
