### ISSUE TITLE
The compressor code should have a credit for the original author

### ISSUE THREAD

**Issue by arnabc** [Tourenathan-G5organisation/SiliCompressor#2]
The `SiliCompressor.java` is identical to the code provided by Ambalika Saha (http://voidcanvas.com/whatsapp-like-image-compression-in-android/) in her blog, at least you should give her due credit either in Readme or in the Source Code of that file.

**Comment by Tourenathan-G5organisation** [comment]
Yes, you are right. I will do so.

**Comment by Tourenathan-G5organisation** [comment]
@arnabc thanks for your point. I have fix the issue on the readme. You can check.
