### ISSUE TITLE
Not able to read file on Android N

### ISSUE THREAD

**Issue by irfaan008** [Tourenathan-G5organisation/SiliCompressor#20]
Android N doesn't support reading from scheme file://. It uses content:// 
Refer : [https://inthecheesefactory.com/blog/how-to-share-access-to-file-with-fileprovider-on-android-nougat/en](https://inthecheesefactory.com/blog/how-to-share-access-to-file-with-fileprovider-on-android-nougat/en)

While running the silicompressor with suggested approach of above link, it gives following exception:

[<img src='https://i.imgur.com/AQN2cKf.png' />]()

Seems silicompressor is failing to read with this new scheme.

**Comment by larrytech7** [comment]
Indeed, we will address that and get you an update. Thanks for pointing this out. We'll create a generalization layer upon which we manage different versions of common Interfaces like this

**Comment by Tourenathan-G5organisation** [comment]
Hello @irfaan008 
We have release a new library version and i'm sure this comes with a solution to your issue.
You can check and let us know
