### ISSUE TITLE
SiliCompressor is not supportting on over Android N.

### ISSUE THREAD

**Issue by DaGeTian** [Tourenathan-G5organisation/SiliCompressor#22]
Hi, 
I loved it before. but now, silicompressor is not supportting on Android N.
Specially Samsung S8. Please confirm it and update, 
Regards,

**Comment by TianDaGe** [comment]
PS: you can check that issue on emulator (API 26).

**Comment by AmanSharma1988** [comment]
Hi TianDaGe i just checked seems like issue with Uri.parse(videoFileUri)) as its returning null in compressVideo method.
As in API 24 and above we need to get uri like this
if (Build.VERSION.SDK_INT >= 24) {
                    fileUri = FileProvider.getUriForFile(mContext, mContext.getApplicationContext()
                            .getPackageName() + ".provider", img);
                } else {
                    fileUri = Uri.fromFile(img);
                }
This i got error while taking image using intent for camera request and passing URI. So seems same here 
I do more deep down and come back soon.

**Comment by engakhamis** [comment]
I was going to use it until I saw your comment. Is the problem fixed now and if not is there any suggestions?

best regards.

**Comment by TianDaGe** [comment]
Video recording is working fine. but image shot has problem yet.

**Comment by Tourenathan-G5organisation** [comment]
Hi @TianDaGe @engakhamis 
We have just release a new version of the library and i think this will resolve your issue.
Please check it and let us know

**Comment by varun7952** [comment]
@Tourenathan-G5organisation It still lags and give unsuccessful compress on API 26 (8.1) Plus it lags the phone too
