### ISSUE TITLE
Small Bug:Delete Photo in Silicompressor

### ISSUE THREAD

**Issue by ziadkiwan** [Tourenathan-G5organisation/SiliCompressor#4]
Hello,
the compressor is great i must admit it's one of the best i used so far, i have a small issue, when i use the getcompressbitmap it returns the bitmap but it doesn't delete the picture inside the silicomfolder on SD how to do that without having the get the image path then transform it to bitmap then delete programmatically as it takes more useless steps (just for performance tuning)

**Comment by Tourenathan-G5organisation** [comment]
Thanks for your feedback.
We will work on it to optimize it. Your feedback had been taken into consideration.

On 2 Mar 2017 12:08 p.m., ziadkiwan <notifications@github.com> wrote:

Hello,
the compressor is great i must admit it's one of the best i used so far, i have a small issue, when i use the getcompressbitmap it returns the bitmap but it doesn't delete the picture inside the silicomfolder on SD how to do that without having the get the image path then transform it to bitmap then delete programmatically as it takes more useless steps (just for performance tuning)

**Comment by ziadkiwan** [comment]
Thank you looking forward for the fix 👍

**Comment by Tourenathan-G5organisation** [comment]
Hello @ziadkiwan ,
If i got your point clearly, you want to be able to specify a parameter in the library that will indicate if the compressed file in Silcompressor folder should be deleted or NOT. i.e You just want the bitmap but not the file

**Comment by ziadkiwan** [comment]
Yes exactly!

**Comment by larrytech7** [comment]
@ziadkiwan check the overloaded method **`compress`** which contains a last parameter boolean that determines whether or not to delete the original image in compressed folder
