### ISSUE TITLE
How to solve duplicate com.googlecode.mp4parser

### ISSUE THREAD

**Issue by developerGM** [Tourenathan-G5organisation/SiliCompressor#41]
Why not add this in build.gradle ?

`compile 'com.googlecode.mp4parser:isoparser:1.1.20'`

instead of using a static .jar library ?
Because this way you can quickly update your library `isoparser ` and if a user want use your `SiliCompressor ` can exlude in his build `isoparser ` if he is using in another library (so solve duplicate problem)

**Comment by Tourenathan-G5organisation** [comment]
THis is solved in version 2.2.3
