### ISSUE TITLE
Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'. > com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

### ISSUE THREAD

**Issue by agi-umar** [Tourenathan-G5organisation/SiliCompressor#49]
Getting dex error

**Comment by FranciscoNin** [comment]
same here

**Comment by andriodfamami** [comment]
you find the solution bro ????

**Comment by agi-umar** [comment]
Well I found a solution, the problem in my case is isoparser package which is used in this library.
I also used another library which also using the same package so both are confliting.
So I changed my code of dependency like 

```
implementation(project(':k4l-video-trimmer')) {
       transitive = false
    }
```
by using above code my problem is solved. You guys also need to check by running stack trace to check which dependency is  conflicting

**Comment by andriodfamami** [comment]
i dont inderstand  bro

Envoyé à partir d’Outlook<http://aka.ms/weboutlook>


________________________________
De : Agi Umar <notifications@github.com>
Envoyé : vendredi 9 février 2018 07:04
À : Tourenathan-G5organisation/SiliCompressor
Cc : andriodfamami; Comment
Objet : Re: [Tourenathan-G5organisation/SiliCompressor] Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'. > com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex (#49)


Well I found a solution, the problem in my case is isoparser package which is used in this library.
I also used another library which also using the same package so both are confliting.
So I changed my code of dependency like

implementation(project(':k4l-video-trimmer')) {
       transitive = false
    }


by using above code my problem is solved. You guys also need to check by running stack trace to check which dependency is conflicting

**Comment by FranciscoNin** [comment]
@agi-umar I was using this same video trimmer library. Thanks!
