### ISSUE TITLE
New Feature Request: Compress Bitmap

### ISSUE THREAD

**Issue by ziadkiwan** [Tourenathan-G5organisation/SiliCompressor#5]
Hello Tourenathan, is there a way to compress a bitmap directly ? give the bitmap through the constructor not an image URI ? thank you.

**Comment by Ali-Jamali** [comment]
i do it by adding this code to SiliCompressor.java  

`
   public Uri getImageUri(Context inContext, Bitmap inImage) {
        ByteArrayOutputStream bytes = new ByteArrayOutputStream();
        inImage.compress(Bitmap.CompressFormat.JPEG, 100, bytes);
        String path = MediaStore.Images.Media.insertImage(inContext.getContentResolver(), inImage, "Title", null);
        return Uri.parse(path);
    }

    public String getRealPathFromURI(Uri uri) {
        Cursor cursor = mContext.getContentResolver().query(uri, null, null, null, null);
        cursor.moveToFirst();
        int idx = cursor.getColumnIndex(MediaStore.Images.ImageColumns.DATA);
        return cursor.getString(idx);
    }


    public Bitmap getCompressBitmap(Bitmap image, boolean deleteSourceImage) throws IOException {
        Uri tempUri = getImageUri(mContext, image);
        File imageFile = new File(compressImage(getRealPathFromURI(tempUri)));
        Uri newImageUri = Uri.fromFile(imageFile);
        Bitmap bitmap = MediaStore.Images.Media.getBitmap(mContext.getContentResolver(), newImageUri);
        if (deleteSourceImage)
        {
            File source = new File(getRealPathFromURI(getRealPathFromURI(tempUri)));
            if (source.exists()) {
                boolean isdeleted = source.delete();
                Log.d(LOG_TAG, (isdeleted) ? "SourceImage File deleted" : "SourceImage File not deleted");
            }
        }
        return bitmap;
    }


`

than you can use it like this 

`
     try{
                             imageBitmap = SiliCompressor.with(context).getCompressBitmap(resource, true);
                        }catch (Exception e){
                            Log.e("SiliCompressor","Error ");
                        }
`

**Comment by Ali-Jamali** [comment]
i do it by adding this code to SiliCompressor.java  

```
    public Uri getImageUri(Context inContext, Bitmap inImage) {
        ByteArrayOutputStream bytes = new ByteArrayOutputStream();
        inImage.compress(Bitmap.CompressFormat.JPEG, 100, bytes);
        String path = MediaStore.Images.Media.insertImage(inContext.getContentResolver(), inImage, "Title", null);
        return Uri.parse(path);
    }

    public String getRealPathFromURI(Uri uri) {
        Cursor cursor = mContext.getContentResolver().query(uri, null, null, null, null);
        cursor.moveToFirst();
        int idx = cursor.getColumnIndex(MediaStore.Images.ImageColumns.DATA);
        return cursor.getString(idx);
    }

    public Bitmap getCompressBitmap(Bitmap image, boolean deleteSourceImage) throws IOException {
        Uri tempUri = getImageUri(mContext, image);
        File imageFile = new File(compressImage(getRealPathFromURI(tempUri)));
        Uri newImageUri = Uri.fromFile(imageFile);
        Bitmap bitmap = MediaStore.Images.Media.getBitmap(mContext.getContentResolver(), newImageUri);
        if (deleteSourceImage)
        {
            File source = new File(getRealPathFromURI(getRealPathFromURI(tempUri)));
            if (source.exists()) {
                boolean isdeleted = source.delete();
                Log.d(LOG_TAG, (isdeleted) ? "SourceImage File deleted" : "SourceImage File not deleted");
            }
        }
        return bitmap;
    }
```

than you can use it like this 


```
try{
	imageBitmap = SiliCompressor.with(context).getCompressBitmap(BitmapResource, true);
}catch (Exception e){
	Log.e("SiliCompressor","Error ");
}

```

**Comment by Tourenathan-G5organisation** [comment]
@ziadkiwan @Ali-Jamali 
I will see into it to include this method in the next version
