### ISSUE TITLE
unable to build project after implementing the siliCompressor in  gradle 

### ISSUE THREAD

**Issue by Virendra-Varma** [Tourenathan-G5organisation/SiliCompressor#64]
Program type already present: com.coremedia.iso.BoxParser
Message{kind=ERROR, text=Program type already present: com.coremedia.iso.BoxParser, sources=[Unknown source file], tool name=Optional.of(D8)}

**Comment by Virendra-Varma** [comment]
getting this problem because of mp4parser. In my app.gradle I am using version no 1.1.21 u guys are using the different version of it, this is dex merging issue

**Comment by pranav-md** [comment]
I'm facing the same issue..how did you solve it?

**Comment by Virendra-Varma** [comment]
Add siliCompressor as a module to project, remove lib jar and add mp4parser by implementing it in gradle file by this problem will the problem was solved not getting any error but after compressing video what I found the audio is not there in the file. If you have time then try this and if find any solution please share with us thanks.

**Comment by pranav-md** [comment]
Thanks for the reply :) 👍

**Comment by pranav-md** [comment]
Im also stucked with the same no-audio issue....tried all solutions found
