### ISSUE TITLE
It's removing the audio from video file

### ISSUE THREAD

**Issue by Virendra-Varma** [Tourenathan-G5organisation/SiliCompressor#65]
I am Recording the video using media recorder and camera api2 and property of my audio is 

mMediaRecorder.setAudioSource(MediaRecorder.AudioSource.MIC);
            mMediaRecorder.setVideoSource(MediaRecorder.VideoSource.SURFACE);
            mMediaRecorder.setOutputFormat(MediaRecorder.OutputFormat.MPEG_4);

            mMediaRecorder.setOutputFile(filePath);
            //        mMediaRecorder.setVideoEncodingBitRate(10000000);
            mMediaRecorder.setVideoEncodingBitRate(3000000);
            mMediaRecorder.setVideoFrameRate(24);
            mMediaRecorder.setVideoSize(recordingVideoSize.getWidth(), recordingVideoSize.getHeight());
            mMediaRecorder.setVideoEncoder(MediaRecorder.VideoEncoder.H264);
            mMediaRecorder.setAudioEncoder(MediaRecorder.AudioEncoder.AAC);
            mMediaRecorder.setAudioEncodingBitRate(16000);

after compressing video file using silicomressor there is no audio in result

**Comment by SanjayGubaju** [comment]
I had same issue with audio. It does not work.

**Comment by Tourenathan-G5organisation** [comment]
Good @SanjayGubaju i'm happy you found a solution to this problem.
@Virendra-Varma Please check the comment done by @SanjayGubaju above.

**Comment by Virendra-Varma** [comment]
Hi @SanjayGubaju, @Tourenathan-G5organisation thanks for the reply. I am not testing you solution  because my app is video uploading app may b your solution work but what if someone record video from the primary camera app and try to upload video at that time it is not helpful for me  

thanks

**Comment by pranav-md** [comment]
@SanjayGubaju thanks for the reply..can we able to change the audio encoder to HE_ACC of a video file or when we record video using external camera apps by.... intent = new Intent(MediaStore.ACTION_VIDEO_CAPTURE);..?

**Comment by MNikdan** [comment]
@SanjayGubaju can you please explain how did you change the audio encoder?

**Comment by ashwinvishesh** [comment]
> @SanjayGubaju thanks for the reply..can we able to change the audio encoder to HE_ACC of a video file or when we record video using external camera apps by.... intent = new Intent(MediaStore.ACTION_VIDEO_CAPTURE);..?

Hey @SanjayGubaju did you find a solution for this ? coz i am also currently in this exact same situation. did you figure out a way to change the audio encoder while recording video using intent(MediaStore.ACTION_VIDEO_CAPTURE) ?
