### ISSUE TITLE
Problem with mp4parser

### ISSUE THREAD

**Issue by MasoudBNJ** [Tourenathan-G5organisation/SiliCompressor#68]
I'm using the 1.1.21 version of mp4parser(isoparser) in my project and when I add SiliCompressor and build my project the gradle gives an error: 'Duplicate zip error'. Because exists two isoparser library in my project (one for myself and another for SiliCompressor). but I need both of them and don't want to remove any of them. So how to handle this problem?
(The version of SiliCompressor's isoparser library is 1.0.6).

**Comment by Tourenathan-G5organisation** [comment]
Solved, check v2.2.3
