### ISSUE TITLE
Cannot find 2.2 version in gradle

### ISSUE THREAD

**Issue by hadiidbouk** [Tourenathan-G5organisation/SiliCompressor#72]

**Comment by Tourenathan-G5organisation** [comment]
Hi @hadiidbouk  yes for let us know. We just found that the library was not properly build for v2.2 
We are working to correct this.
Please while waiting you can use v2.1

**Comment by Tourenathan-G5organisation** [comment]
Hello @hadiidbouk  the issue has been solved now.
Sorry for the convenience and thanks for your prompt reaction. The current stable library version is 2.2.1
