### ISSUE TITLE
Failed to resolve : silicompressor

### ISSUE THREAD

**Issue by mg25071998** [Tourenathan-G5organisation/SiliCompressor#73]
I am getting a error at time of build that 

Failed to resolve : dependency of silicompressor

**Comment by mg25071998** [comment]
Receiving this only on version 2.2 not any other

**Comment by Tourenathan-G5organisation** [comment]
Hi, @mg25071998 sorry for this error. I have just realize that the library was not properly build for this version. I'm working on it to fix this error. While waiting please use the version 2.1

**Comment by Tourenathan-G5organisation** [comment]
Hello @mg25071998 the issue has been solved now.
Sorry for the convenience and thanks for your prompt reaction. The current stable library version is 2.2.1
