### ISSUE TITLE
INSTALL_FAILED_CONFLICTING_PROVIDER

### ISSUE THREAD

**Issue by pedrofsn** [Tourenathan-G5organisation/SiliCompressor#82]
I've a project with multiple modules like:

- A (application)
- B (application)
- Core (library)

Modules A and B dependes of module Core.

SiliCompressor is in module Core and used in module A. 
I've app A (from module A) installed.
When I try to install aplication/module B in same emuator that is running SiliCompressor I got this error message bellow. How can I handle this?

> Installation failed with message INSTALL_FAILED_CONFLICTING_PROVIDER.
> It is possible that this issue is resolved by uninstalling an existing version of the apk if it is present, and then re-installing.
> 
> WARNING: Uninstalling will remove the application data!
> 
> Do you want to uninstall the existing application?
>

**Comment by LoAlex** [comment]
same problem, how you fix it finally?

**Comment by pedrofsn** [comment]
I haven't fixed, the problem goes on @LoAlex.

**Comment by LoAlex** [comment]
> I haven't fixed, the problem goes on @LoAlex.

I have fixed, try to add below code.

        <provider
                tools:replace="android:authorities"
                android:name="com.iceteck.silicompressorr.provider.GenericFileProvider"
                android:authorities="${applicationId}.AUTH_SILI_COMPRESS"
                android:exported="false" />

**Comment by pedrofsn** [comment]
Thanks @LoAlex, it's worked!

**Comment by kristiyanP** [comment]
Another solution is to remove the provider that should not exist in a library in the first place...
by using tools:node="remove"

``` xml
<provider
            android:name="com.iceteck.silicompressorr.provider.GenericFileProvider"
            android:authorities="com.iceteck.silicompressor.provider"
            android:exported="false"
            tools:node="remove"
            tools:replace="android:authorities" />
```

**Comment by kristiyanP** [comment]
@Tourenathan-G5organisation you should highly consider to remove it is not something that should be in a library.
