### ISSUE TITLE
Surface frame wait time out and screen goes black

### ISSUE THREAD

**Issue by abinmittu** [Tourenathan-G5organisation/SiliCompressor#84]
Hi, First of all. I am not an android developer. I am currently working on a project based on Flutter where i am trying to use SiliCompressor to compress videos on the android side of project. I followed your readme and added implementation to gradle, but when i am using 

`String filePath = SiliCompressor.with(MainActivity.this).compressVideo(videoPath, destinationDirectory);`

i am getting a message Surface frame wait timed out and screen goes black.

**Comment by Tourenathan-G5organisation** [comment]
Hi @abinmittu,Yes, check if the SiliCompressor is imported in your activity or fragment?

**Comment by abinmittu** [comment]
Yes. But when I am trying to compress a video this is what i get in console

D/ExtendedUtils(26264): extended extractor not needed, return default
E/tmessages(26264): colorFormat = 2130708361
I/MediaCodec(26264): name=video/avc isType=true encoder=true
I/OMXClient(26264): Using client-side OMX mux.
E/ACodec  (26264): [OMX.qcom.video.encoder.avc] storeMetaDataInBuffers (output) failed w/ err -1010
W/ACodec  (26264): do not know color format 0x7fa30c04 = 2141391876
W/ACodec  (26264): do not know color format 0x7f000789 = 2130708361
I/ACodec  (26264): setupVideoEncoder succeeded
W/ACodec  (26264): do not know color format 0x7f000789 = 2130708361
I/MediaCodec(26264): name=video/avc isType=true encoder=false
I/OMXClient(26264): Using client-side OMX mux.
I/MediaCodec(26264): [OMX.qcom.video.decoder.avc] setting surface generation to 26894337
I/ACodec  (26264): DRC Mode: Dynamic Buffer Mode
I/ExtendedCodec(26264): Decoder will be in frame by frame mode
D/SurfaceUtils(26264): set up nativeWindow 0xb9cf20a8 for 400x224, color 0x7fa30c04, rotation 0, usage 0x42002900
D/SurfaceUtils(26264): set up nativeWindow 0xb9cf20a8 for 400x224, color 0x7fa30c04, rotation 0, usage 0x42002900
E/tmessages(26264): newFormat = {mime=video/raw, crop-top=0, crop-right=399, slice-height=224, color-format=2141391876, height=224, width=400, what=1869968451, crop-bottom=223, crop-left=0, stride=512}
E/tmessages(26264): Surface frame wait timed out
E/tmessages(26264): Surface frame wait timed out
E/tmessages(26264): Surface frame wait timed out

Surface frame wait time out gets printed repeatedly and then screen goes black

**Comment by harikumar007** [comment]
For me also...

**Comment by mayanktripathi87** [comment]
but, i have fixed it as i did the compression on a new thread, now it works fine

**Comment by Tourenathan-G5organisation** [comment]
@mayanktripathi87 good to know. Please @harikumar007 and @abinmittu you should try to compress on a new thread and see if it solves the problem

**Comment by harikumar007** [comment]
Running on new thread solved the issue.
Thanks

**Comment by Tourenathan-G5organisation** [comment]
Great! Happy to know it works.

**Comment by sharks20** [comment]
hi guys any sample codes on the same, would be appreciated

**Comment by My-Projects-24-X-7** [comment]
Code please.

**Comment by thangbkhn** [comment]
> but, i have fixed it as i did the compression on a new thread, now it works fine

Thank so much
