### ISSUE TITLE
File Not Found when folder contain symbol (!@#$%^&* etc)

### ISSUE THREAD

**Issue by firdausmaulan** [Tourenathan-G5organisation/SiliCompressor#9]
E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /storage/emulated/0/asd: open failed: ENOENT (No such file or directory)

**Comment by larrytech7** [comment]
I think your folder shouldn't contain those symbols, then. Are you trying to specify a source folder or a destination folder?

**Comment by Tourenathan-G5organisation** [comment]
@firdausmaulan which file was not able to be found.
The source or destination? Also, avoid using path with those symbols.

**Comment by firdausmaulan** [comment]
@larrytech7 There are some users who use symbol for naming folder, and it's causes an error.
As example "District #12"
`E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /storage/emulated/0/District: open failed: ENOENT (No such file or directory)`

**Comment by firdausmaulan** [comment]
@Tourenathan-G5organisation I think the library cannot find the source file.

**Comment by Tourenathan-G5organisation** [comment]
@firdausmaulan The library get the source file based on the given uriString you passed as parameter. Are you sure the file exist? Also are you sure the it respect the naming convention?

**Comment by prasad456** [comment]
> @firdausmaulan which file was not able to be found.
> The source or destination? Also, avoid using path with those symbols.

this works after removing my, but my path doesn't contain any special char except _

**Comment by Tourenathan-G5organisation** [comment]
@prasad456 so it works well when you remove special symbols from the path, right?
