### ISSUE TITLE
Can only use 1 app together using silicompressor

### ISSUE THREAD

**Issue by Inshaki** [Tourenathan-G5organisation/SiliCompressor#96]
I am currently using 2 apps with silicompressor, but I have to delete App A before I can run App B in Android Studio. 

Also I want to use the debug and release version in my app. But when I have the debug app and want to download the app in the playstore, I get an error from the playstore.

![Schermafbeelding 2019-04-11 om 09 23 52](https://user-images.githubusercontent.com/37954248/55938698-347e5b00-5c3c-11e9-886b-76fe8c122512.png)

**Comment by Tourenathan-G5organisation** [comment]
Hi @Inshaki 
thanks for this feedback. I see that i error comes as a result of file provider conflicts. I will search on it and see how we can resolve that. Also, please let me know if on your side you find a possible solution so that i can also test and integrate if OK.

**Comment by Inshaki** [comment]
Hi @Tourenathan-G5organisation 

Thanks for your reply, I checked it quite long, but I could not find the solution for this. Do you have any updates?

**Comment by xiyang1321lz** [comment]
I modified the code to make it universal to all apps and create a pull request.

**Comment by Tourenathan-G5organisation** [comment]
@Jack-TianTan Thanks for your solution. Its now merged with the repo
@Inshaki problem solved now
