### ISSUE TITLE
two project,I'm quote this.remaind me A project cannot be installed

### ISSUE THREAD

**Issue by wangweishou123** [Tourenathan-G5organisation/SiliCompressor#99]
this remain me because name com.iceteck.silicompressor.provider is already used by other project

**Comment by Tourenathan-G5organisation** [comment]
@wangweishou123 This problem is solved today with the new version of the library release today.
Check version 2.2.2

Let me know if OK

**Comment by eclipsed4utoo** [comment]
@Tourenathan-G5organisation Any chance you could publish a new version for the Nuget package for Xamarin support? I'm running into this issue, but the latest version is 2.2.1 on Nuget.
